#!/bin/bash

ICON=/tmp/xkcd #might be png or jpg, identify from imagemagick will know
TMPBG=/home/hjolli/Pictures/Backgrounds/i3back.png
#SCALE=`xdpyinfo  | grep -oP 'dimensions:\s+\K\S+'`
SCALE=`/usr/bin/xrandr |head -1 | awk -F"," '{print $2}' | awk '{print $2"x"$4}'`

function main {
	if [[ ! -e $ICON ]]; then
		checkinternet > /dev/null 2>&1
		download_xkcd &
		wait
	fi
	if [[ ! -e $TMPBG ]]; then
		iconresize
		wait
		getBackground &
		wait
		embedComic
	fi

	i3lock -c 000000 -i $TMPBG &
	iconresize
	wait
	getBackground &
	checkinternet > /dev/null 2>&1
	download_xkcd &
	wait
	embedComic &
	#cleanup
}

function checkinternet {
	if ping -q -c 1 -W 1 8.8.8.8 >/dev/null; then
  	echo "we have connection"
	else
	exit 
	fi
}

function iconresize {
	if [ ${SCALE} = "3840x2160" ]
	then
		RESIZE=250%
		DORESIZE="-resize ${RESIZE}"
	else
		RESIZE=100%
		DORESIZE=""
	fi
}

function download_xkcd {
	local NUMCOMICS=$(curl -sL "http://xkcd.com/info.0.json" | grep -oP '(?<=num": )([^,]*)')
	local COMIC=404
	until [[ "$COMIC" -ne "404" ]]; do
		COMIC=$((1 + RANDOM % $NUMCOMICS))
	done
	local URL=$(curl -sL "http://xkcd.com/$COMIC/info.0.json" | grep -oP '(?<=img": ")([^"]*)' | tr -d '\\')
	curl -sL "$URL" -o $ICON
}

function getBackground {
	IMG=`ls /home/hjolli/Pictures/Backgrounds/PNG/*.png | shuf -n 1`
	convert -resize ${SCALE} ${IMG} $TMPBG
}

function embedComic {
	#lockscreen image info
	local C_C=($(identify -format "%w %h" $ICON))
	local SCREENS=$(xrandr --query | grep ' connected' | grep -o '[0-9][0-9]*x[0-9][0-9]*[^ ]*')
	if [[ -f "$ICON" ]]; then
		local COMM=""
		for RES in $SCREENS; do
			# monitor position/offset
			local C_S=(${RES//[x+]/ })
			local PX=$((${C_S[2]} + ${C_S[0]} / 16 - ${C_C[0]} / 16))
			local PY=$((${C_S[3]} + ${C_S[1]} / 16 - ${C_C[1]} / 16))
			if [[ "$COMM" == "" ]]; then
				COMM="convert $TMPBG \( $ICON ${DORESIZE} -repage +$PX+$PY \) "
			else
				COMM="${COMM}\( +clone -repage +$PX+$PY \) " #avoid extra file reads
			fi
		done
		COMM="${COMM}-layers flatten $TMPBG"
		eval $COMM
	fi
}

function cleanup {
	rm $TMPBG
	#rm $ICON
}

main "$@"

